ci: printing of the toolchain versions added

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -13,12 +13,12 @@ name: "CodeQL"
 
 on:
   push:
-    branches: [ "master" ]
+    branches: ["master"]
     paths-ignore:
       - "docs/**"
   pull_request:
     # The branches below must be a subset of the branches above
-    branches: [ "master" ]
+    branches: ["master"]
     paths-ignore:
       - "docs/**"
 
@@ -51,67 +51,74 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        language: [ 'cpp', 'python' ]
+        language: ["cpp", "python"]
         # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby', 'swift' ]
         # Use only 'java' to analyze code written in Java, Kotlin or both
         # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
         # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    # Initializes the CodeQL tools for scanning.
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
+      # Initializes the CodeQL tools for scanning.
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v3
+        with:
+          languages: ${{ matrix.language }}
+          # If you wish to specify custom queries, you can do so here or in a config file.
+          # By default, queries listed here will override any specified in a config file.
+          # Prefix the list here with "+" to use these queries and those in the config file.
 
-        # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
+          # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+          # queries: security-extended,security-and-quality
 
+      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
+      # If this step fails, then you should remove it and run the build manually (see below)
+      - name: Autobuild
+        if: matrix.language != 'cpp'
+        uses: github/codeql-action/autobuild@v3
 
-    # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
-    # If this step fails, then you should remove it and run the build manually (see below)
-    - name: Autobuild
-      if: matrix.language != 'cpp'
-      uses: github/codeql-action/autobuild@v3
+      # ℹ️ Command-line programs to run using the OS shell.
+      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
 
-    # ℹ️ Command-line programs to run using the OS shell.
-    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+      - run: echo "cache_id=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_ENV
+      - name: Cache Conan data
+        if: matrix.language == 'cpp'
+        uses: actions/cache@v4
+        env:
+          cache-name: cache-conan-data
+        with:
+          path: ~/.conan2/p
+          key: build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-$COMPILER_VERSION-$STDLIB-${{ env.cache_id }}
+          restore-keys: |
+            build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-$COMPILER_VERSION-$STDLIB-
+            build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-
+            build-${{ matrix.os }}-$BUILD_TYPE-
+            build-${{ matrix.os }}-
+      - name: Set up Python
+        if: matrix.language == 'cpp'
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.x
+      - name: Print tool versions
+        if: matrix.language == 'cpp'
+        shell: bash
+        run: |
+          ${CXX} --version
+          cmake --version 2>&1 || true
+          python3 --version
+      - name: Conan build
+        if: matrix.language == 'cpp'
+        run: |
+          pip install -U conan
+          conan --version
+          conan profile detect --force
+          conan remote add artifactory https://mpusz.jfrog.io/artifactory/api/conan/conan-oss
+          mkdir _lgtm_build_dir && cd _lgtm_build_dir
+          conan build .. -s compiler.cppstd=20 -c user.mp-units.build:all=True -o '&:std_format=False' -b missing
 
-    - run: echo "cache_id=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_ENV
-    - name: Cache Conan data
-      if: matrix.language == 'cpp'
-      uses: actions/cache@v4
-      env:
-        cache-name: cache-conan-data
-      with:
-        path: ~/.conan2/p
-        key: build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-$COMPILER_VERSION-$STDLIB-${{ env.cache_id }}
-        restore-keys: |
-          build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-$COMPILER_VERSION-$STDLIB-
-          build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-
-          build-${{ matrix.os }}-$BUILD_TYPE-
-          build-${{ matrix.os }}-
-    - name: Set up Python
-      if: matrix.language == 'cpp'
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.x
-    - name: Conan build
-      if: matrix.language == 'cpp'
-      run: |
-        pip install -U conan
-        conan profile detect --force
-        conan remote add artifactory https://mpusz.jfrog.io/artifactory/api/conan/conan-oss
-        mkdir _lgtm_build_dir && cd _lgtm_build_dir
-        conan build .. -s compiler.cppstd=20 -c user.mp-units.build:all=True -o '&:std_format=False' -b missing
-
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        category: "/language:${{matrix.language}}"
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v3
+        with:
+          category: "/language:${{matrix.language}}"
